// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import * as path from 'path';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { Construct } from 'constructs';

/**
 * Props for GetPlantsFunction
 */
export interface GetPlantsFunctionProps extends lambda.FunctionOptions {
}

/**
 * An AWS Lambda function which executes src/backend/plants-functions/get-plants.
 */
export class GetPlantsFunction extends lambda.Function {
  constructor(scope: Construct, id: string, props?: GetPlantsFunctionProps) {
    super(scope, id, {
      description: 'src/backend/plants-functions/get-plants.lambda.ts',
      ...props,
      runtime: new lambda.Runtime('nodejs16.x', lambda.RuntimeFamily.NODEJS),
      handler: 'index.handler',
      code: lambda.Code.fromAsset(path.join(__dirname, '../../../assets/backend/plants-functions/get-plants.lambda')),
    });
    this.addEnvironment('AWS_NODEJS_CONNECTION_REUSE_ENABLED', '1', { removeInEdge: true });
  }
}